/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ijPfLXkPQLx
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { CardContent, Card } from "@/components/ui/card"

export function Incedents() {
  return (
    <div className="grid gap-4 md:grid-cols-[1fr_300px]">
      <div className="rounded-lg border border-gray-200 shadow-sm dark:border-gray-800">
        <div className="flex items-center justify-between p-4 border-b">
          <h1 className="text-xl font-semibold">Incident Management</h1>
          <div className="flex gap-2">
            <Button className="h-8 w-8" size="icon" variant="ghost">
              <RefreshCwIcon className="w-4 h-4" />
              <span className="sr-only">Refresh</span>
            </Button>
            <Button className="h-8 w-8" size="icon" variant="ghost">
              <SettingsIcon className="w-4 h-4" />
              <span className="sr-only">Settings</span>
            </Button>
          </div>
        </div>
        <div className="p-4">
          <div className="grid w-full gap-2">
            <div className="flex items-center gap-2">
              <SearchIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input className="min-w-0 flex-1" placeholder="Search incidents..." type="search" />
            </div>
            <div className="grid w-full overflow-auto min-h-[300px] border border-gray-200 rounded-lg dark:border-gray-800">
              <table className="w-full text-left border-collapse text-sm">
                <thead>
                  <tr>
                    <th className="p-2 font-normal border-b-0">ID</th>
                    <th className="p-2 font-normal border-b-0">Severity</th>
                    <th className="p-2 font-normal border-b-0">Description</th>
                    <th className="p-2 font-normal border-b-0">Status</th>
                    <th className="p-2 font-normal border-b-0">Assigned to</th>
                    <th className="p-2 font-normal border-b-0">Last updated</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="hover:bg-gray-100/40 dark:hover:bg-gray-800/40">
                    <td className="p-2">INC001</td>
                    <td className="p-2">High</td>
                    <td className="p-2">Database server is not responding to requests</td>
                    <td className="p-2">Open</td>
                    <td className="p-2">Alice Johnson</td>
                    <td className="p-2">2 minutes ago</td>
                  </tr>
                  <tr className="hover:bg-gray-100/40 dark:hover:bg-gray-800/40">
                    <td className="p-2">INC002</td>
                    <td className="p-2">Low</td>
                    <td className="p-2">Email server is experiencing intermittent delays</td>
                    <td className="p-2">Open</td>
                    <td className="p-2">Bob Smith</td>
                    <td className="p-2">5 minutes ago</td>
                  </tr>
                  <tr className="hover:bg-gray-100/40 dark:hover:bg-gray-800/40">
                    <td className="p-2">INC003</td>
                    <td className="p-2">Medium</td>
                    <td className="p-2">Website is showing a 404 error for some users</td>
                    <td className="p-2">Open</td>
                    <td className="p-2">Charlie Brown</td>
                    <td className="p-2">10 minutes ago</td>
                  </tr>
                  <tr className="hover:bg-gray-100/40 dark:hover:bg-gray-800/40">
                    <td className="p-2">INC004</td>
                    <td className="p-2">High</td>
                    <td className="p-2">Network connectivity issues in the office</td>
                    <td className="p-2">Open</td>
                    <td className="p-2">David Lee</td>
                    <td className="p-2">15 minutes ago</td>
                  </tr>
                  <tr className="hover:bg-gray-100/40 dark:hover:bg-gray-800/40">
                    <td className="p-2">INC005</td>
                    <td className="p-2">Low</td>
                    <td className="p-2">Printer is not printing documents correctly</td>
                    <td className="p-2">Open</td>
                    <td className="p-2">Eva Wilson</td>
                    <td className="p-2">20 minutes ago</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div className="rounded-lg border border-gray-200 shadow-sm dark:border-gray-800">
        <div className="flex items-center justify-between p-4 border-b">
          <h1 className="text-xl font-semibold">Workflow Integration</h1>
          <div className="flex gap-2">
            <Button className="h-8 w-8" size="icon" variant="ghost">
              <RefreshCwIcon className="w-4 h-4" />
              <span className="sr-only">Refresh</span>
            </Button>
            <Button className="h-8 w-8" size="icon" variant="ghost">
              <SettingsIcon className="w-4 h-4" />
              <span className="sr-only">Settings</span>
            </Button>
          </div>
        </div>
        <div className="p-4">
          <div className="grid gap-2">
            <div className="flex items-center gap-2">
              <SearchIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input placeholder="Search incidents..." type="search" />
            </div>
            <div className="grid gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <div>AL</div>
                </Avatar>
                <div className="flex-1 grid gap-1 text-xs">
                  <div className="font-semibold">Alice Johnson</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">Senior Analyst</div>
                </div>
                <div className="flex-1 grid gap-1 text-xs">
                  <div className="font-semibold">Assigned to</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">INC001, INC002, INC003</div>
                </div>
              </div>
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <Avatar className="w-8 h-8">
                    <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                    <div>BS</div>
                  </Avatar>
                  <div className="flex-1 grid gap-1 text-xs">
                    <div className="font-semibold">Bob Smith</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">Support Engineer</div>
                  </div>
                  <div className="flex-1 grid gap-1 text-xs">
                    <div className="font-semibold">Assigned to</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">INC004, INC005</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="grid gap-2">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <div>CB</div>
                </Avatar>
                <div className="flex-1 grid gap-1 text-xs">
                  <div className="font-semibold">Charlie Brown</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">Security Analyst</div>
                </div>
                <div className="flex-1 grid gap-1 text-xs">
                  <div className="font-semibold">Assigned to</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">INC006, INC007</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="rounded-lg border border-gray-200 shadow-sm dark:border-gray-800">
        <div className="flex items-center justify-between p-4 border-b">
          <h1 className="text-xl font-semibold">Incident Timeline</h1>
          <div className="flex gap-2">
            <Button className="h-8 w-8" size="icon" variant="ghost">
              <RefreshCwIcon className="w-4 h-4" />
              <span className="sr-only">Refresh</span>
            </Button>
            <Button className="h-8 w-8" size="icon" variant="ghost">
              <SettingsIcon className="w-4 h-4" />
              <span className="sr-only">Settings</span>
            </Button>
          </div>
        </div>
        <div className="p-4">
          <div className="grid gap-4">
            <div className="flex items-start gap-4">
              <div className="grid gap-0.5 text-xs">
                <time className="font-semibold">10:00 AM</time>
                <time className="text-gray-500 dark:text-gray-400">2 days ago</time>
              </div>
              <Card className="flex-1 shadow-none">
                <CardContent className="p-4">
                  <p className="font-semibold">Incident created</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Incident INC001 was created by Alice Johnson (alice@example.com)
                  </p>
                </CardContent>
              </Card>
            </div>
            <div className="flex items-start gap-4">
              <div className="grid gap-0.5 text-xs">
                <time className="font-semibold">10:00 AM</time>
                <time className="text-gray-500 dark:text-gray-400">2 days ago</time>
              </div>
              <Card className="flex-1 shadow-none">
                <CardContent className="p-4">
                  <p className="font-semibold">Incident created</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Incident INC001 was created by Alice Johnson (alice@example.com)
                  </p>
                </CardContent>
              </Card>
            </div>
            <div className="flex items-start gap-4">
              <div className="grid gap-0.5 text-xs">
                <time className="font-semibold">10:00 AM</time>
                <time className="text-gray-500 dark:text-gray-400">2 days ago</time>
              </div>
              <Card className="flex-1 shadow-none">
                <CardContent className="p-4">
                  <p className="font-semibold">Incident created</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Incident INC001 was created by Alice Johnson (alice@example.com)
                  </p>
                </CardContent>
              </Card>
            </div>
            <div className="flex items-start gap-4">
              <div className="grid gap-0.5 text-xs">
                <time className="font-semibold">10:00 AM</time>
                <time className="text-gray-500 dark:text-gray-400">2 days ago</time>
              </div>
              <Card className="flex-1 shadow-none">
                <CardContent className="p-4">
                  <p className="font-semibold">Incident created</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Incident INC001 was created by Alice Johnson (alice@example.com)
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function RefreshCwIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
