/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aGMByCajH79
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Pagination } from "@/components/ui/pagination"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function k() {
  return (
    <div className="flex flex-col w-full gap-2">
      <div className="rounded-lg border border-gray-200 dark:border-gray-800 dark:border-gray-800">
        <div className="grid w-full grid-cols-[1fr_40px] bg-gray-100/40 dark:bg-gray-800/40">
          <div className="flex items-center h-10 gap-2 px-2">
            <SearchIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input
              className="text-sm bg-transparent border-0 shadow-none appearance-none w-1/3 md:w-1/4 lg:w-1/6"
              placeholder="Search events..."
              type="search"
            />
            <Button className="rounded-full w-8 h-8" size="icon" variant="ghost">
              <FilterIcon className="h-4 w-4" />
              <span className="sr-only">Filter</span>
            </Button>
            <Button className="rounded-full w-8 h-8" size="icon" variant="ghost">
              <RefreshCwIcon className="h-4 w-4" />
              <span className="sr-only">Refresh</span>
            </Button>
            <Button className="rounded-full w-8 h-8 ml-auto" size="icon" variant="ghost">
              <ChevronDownIcon className="h-4 w-4" />
              <span className="sr-only">More</span>
            </Button>
          </div>
          <div className="flex items-center h-8 gap-2 text-xs px-2">
            <span className="font-medium">Showing 1-5 of 100 events</span>
            <Pagination className="ml-auto" />
          </div>
        </div>
        <div className="flex flex-col min-h-[300px]">
          <div className="border-t last:border-b">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[150px]">Event</TableHead>
                  <TableHead className="w-[150px]">Date</TableHead>
                  <TableHead>Description</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">User Login</TableCell>
                  <TableCell>2023-01-01 10:00 AM</TableCell>
                  <TableCell>User with email user@example.com logged in successfully</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">File Upload</TableCell>
                  <TableCell>2023-01-02 11:30 AM</TableCell>
                  <TableCell>User uploaded file1.pdf, file2.jpg, file3.docx</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Payment Success</TableCell>
                  <TableCell>2023-01-03 02:45 PM</TableCell>
                  <TableCell>Payment for order #123456 was successful</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Admin Login</TableCell>
                  <TableCell>2023-01-04 09:20 AM</TableCell>
                  <TableCell>Admin with username admin1 logged in successfully</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Settings Update</TableCell>
                  <TableCell>2023-01-05 03:10 PM</TableCell>
                  <TableCell>User updated their account settings</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </div>
      </div>
    </div>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function RefreshCwIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
